KEYBOARD = {
    'q': 'was',
    'w': 'qsead',
    'e': 'wsdfr',
    'r': 'edfgt',
    't': 'rfghy',
    'y': 'tghju',
    'u': 'yhjki',
    'i': 'ujklo',
    'o': 'iklp',
    'p': 'ol',
    'a': 'qwsxz',
    's': 'qazxcdew',
    'd': 'wsxcvfre',
    'f': 'edcvbgtr',
    'g': 'rfvbnhyt',
    'h': 'tgbnmjuy',
    'j': 'yhnmkiu',
    'k': 'ujmloi',
    'l': 'ikpo',
    'z': 'asx',
    'x': 'zasdc',
    'c': 'xsdfv',
    'v': 'cdfgb',
    'b': 'vfghn',
    'n': 'bghjm',
    'm': 'nhjk'
}
